### ISSUE TITLE
pinned bcftools version libcrypto.so.1.0.0: issue

### ISSUE THREAD

**Issue by fmobegi** [yekaizhou/duet#4]
Am not sure but it seems you have pinned bcftools v1.54  but this raises issues with `libcrypto.so.1.0.0`

**Comment by yekaizhou** [comment]
Hi,

Are you using 'conda install' or 'pip install' for duet?

**Comment by fmobegi** [comment]
conda

**Comment by yekaizhou** [comment]
the libcrypto problem seems is caused by the outdate version of bcftools installed by bioconda. however, we have tested that the version 1.8 of bcftools do not have this problem in multiple of our machines.

anyway, we will have more tests and will make the installation and use of duet more robust. for now, could you please uninstall and reinstall bcftools in the environment of duet, to see if it works?

Yekai

**Comment by yekaizhou** [comment]
reordering the config of conda will possibly solve this problem.

```
conda config --add channels bioconda && conda config --add channels conda-forge
conda create -n duet -c bioconda duet -y && conda activate duet
```

please try the code above to reactivate the environment and reinstall duet, and try the following demo code to see if duet can work:

```
mkdir duet_demo && cd duet_demo
wget 'http://www.bio8.cs.hku.hk/duet_demo_data.tar.gz'
tar -zxvf duet_demo_data.tar.gz && rm duet_demo_data.tar.gz
duet duet_demo_data/HG00733_hg19_chr21.bam duet_demo_data/hg19_chr21.fa results

less results/phased_sv.vcf
```

**Comment by fmobegi** [comment]
I had already fixed it by installing it from the repo.. thanks for the update. Am sure it will be helpful to more people.
